from text_effect import slow_print
from text_effect import loading_anima
from clear_screen import clear_screen
from choose_list import choose_menu
from menu_score import * 
import time

#==========Lối chơi: Lén lút================
def ending_2():
	clear_screen()
	slow_print(" David: ta đã lấy được nó rồi...",0.05)
	time.sleep(1)
	clear_screen()
	slow_print(" David: nhưng làm sao để thoát khỏi đây nhỉ?...",0.05)
	time.sleep(3)
	clear_screen()
	
	while True:
		actions = ["Dùng xe điện lái ra cửa chính","Chui ống thông gió","Chui vào một cái hộp"]
		choice_index, selected_action = choose_menu(actions)
		
		if choice_index == 0:
			clear_screen()
			slow_print(" David: *Khởi động xe điện* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Lái xe điện* ", 0.05)
			clear_screen()
			slow_print(" David: wEEEEE- ", 0.05)
			clear_screen()
			print(" Mà khoang đã...")
			time.sleep(1)
			clear_screen()
			print(" Cái này là ending xông thẳng mà...")
			time.sleep(1)
			clear_screen()
			print(" Mà đây là ending lén lút mà nhỉ?...")
			time.sleep(1)
			clear_screen()
			print(" Chắc là ta nhầm thì phải...")
			time.sleep(3)
			clear_screen()
			fail_display(" SyntaxErorr: Wrong Ending")
			
		elif choice_index == 1:
			clear_screen()
			slow_print(" David: *Tìm ống thông gió* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Đi tới một cái ống thông gió* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: chắc là nó an toàn nhỉ?...",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Chui vào ống thông gió* ", 0.05)
			clear_screen()
			print(" Một lát sau đó...")
			time.sleep(5)
			clear_screen()
			slow_print(" David: *Chui ra ngoài thị trấn* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: :> ", 0.05)
			time.sleep(3)
			clear_screen()
			complete_display(" Amongus £")
			
		elif choice_index == 2:
			clear_screen()
			slow_print(" David: *Chui vào hộp* ", 0.05)
			clear_screen()
			slow_print(" ???: Có một cái thùng ở đây nè!",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" ???: Chắc là nó là rác nhỉ?...",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Ai đó bưng cái hộp đi* ",0.05)
			time.sleep(3)
			clear_screen()
			slow_print(" David: sao có cái mùi gì đó không được thơm thơm nhỉ?... ",0.05)
			clear_screen()
			slow_print(" *David chui khỏi cái hộp và thấy mình ở trên xe rác* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Ngộp thở vì thúi* ",0.05)
			clear_screen()
			fail_display(" "*10 + "David là rác?")
			
def continue_moment2_1():
	slow_print(" David: Viên fitum của ta đây rồi-", 0.05)
	clear_screen()
	slow_print(" David: Cái lớp kính đáng gét này lại không cho ta lấy! ", 0.05)
	clear_screen()
	slow_print(" David: được rồi, tìm cách thôi vậy...", 0.05)
	time.sleep(3)
	clear_screen()
	
	while True:
		actions =["Đập bằng tay","Dùng Laze","Hét vô cái kính","Đứng nhìn"]
		choice_index, selected_action = choose_menu(actions)
		
		if choice_index == 0:
			clear_screen()
			slow_print(" David: *Đập tay vô cái kính* ", 0.05)
			clear_screen()
			slow_print(" David: AAAAA- ",0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" Mày nghĩ cái kính đó là giấy à?")
			
		elif choice_index == 1:
			clear_screen()
			slow_print(" David: *Khởi động laze*",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Cắt cái kính*",0.05)
			clear_screen()
			slow_print(" *Viên kim cương rớt ra ngoài*",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: Viên ngọc quý giá của ta đây rồi :)...", 0.05)
			time.sleep(3)
			ending_2()
					
		elif choice_index == 2:
			clear_screen()
			slow_print(" David: AHGGGG...",0.05)
			clear_screen()
			slow_print(" David: AGHHHHHHHH...",0.05)
			clear_screen()
			slow_print(" David: AGHHHHHHHHHHHHH....", 0.05)
			clear_screen()
			slow_print(" David: *Nhìn lại cái kính* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: sao nó không vỡ nhỉ?...",0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" Mày nghĩ mày là Goku à?")
		
		elif choice_index == 3:
			clear_screen()
			slow_print(" David: *Đứng nhìn* ", 0.05)
			time.sleep(1)
			clear_screen()
			print(" Một lát sau đó...")
			time.sleep(6)
			clear_screen()
			slow_print(" David: <3 ",0.05)
			time.sleep(1)
			clear_screen()
			fail_display(" Tôi không biết nói gì hết...")

def continue_moment2():
	clear_screen()
	slow_print(" David: *đi xung quanh* ",0.05)
	time.sleep(1)
	clear_screen()
	slow_print(" *David đã đi tới một cái ngã 3* ", 0.1)
	time.sleep(1)
	clear_screen()
	slow_print(" David: hm... ",0.05)
	time.sleep(0.5)
	clear_screen()
	slow_print(" David: Nên đi hướng nào đây nhờ?...", 0.05)
	time.sleep(2)
	
	while True:
	  clear_screen()
	  actions = ["Đi sang trái","Đi sang phải","Đi thẳng","Đi ngược về"]
	  choice_index, selected_action = choose_menu(actions)
	  
	  if choice_index == 0:
	  	clear_screen()
	  	slow_print(" David: *Đi sang trái...*", 0.05)
	  	time.sleep(1)
	  	clear_screen()
	  	slow_print(" David: *Đụng tường* ", 0.05)
	  	time.sleep(1)
	  	clear_screen()
	  	slow_print(" David: chỉ là một cái tường thôi mà-", 0.05)
	  	clear_screen()
	  	slow_print(" Factor: *Bay tới và còng tay David* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: ._. ", 0.05)
	  	time.sleep(3)
	  	clear_screen()
	  	fail_display(" Cái game này cần độ hoạ nhỉ?...")
	  	
	  elif choice_index == 1:
	  	clear_screen()
	  	slow_print(" David: *Đi sang phải* ", 0.05)
	  	time.sleep(1)
	  	clear_screen()
	  	print(" Một lát sau đó...")
	  	time.sleep(5)
	  	clear_screen()
	  	continue_moment2_1()
	  	
	  elif choice_index == 2:
	  	clear_screen()
	  	slow_print(" David: *Đi thẳng tới...* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: *Đi thẳng tới...* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: *Đi thẳng tới...* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: *Đi thẳng tới...* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: *Đi thẳng tới...* ", 0.05)
	  	clear_screen()
	  	slow_print(" David: *Mệt quá ngất xỉu...* ", 0.05)
	  	time.sleep(3)
	  	clear_screen()
	  	fail_display(" Hành lang vô tận?")
	  	
	  elif choice_index == 3:
	  	clear_screen()
	  	slow_print(" *David đi ngược về*", 0.05)
	  	time.sleep(1)
	  	clear_screen()
	  	slow_print(" Facto: chào em trai nhé!", 0.05)
	  	clear_screen()
	  	slow_print(" David: ^_^ ", 0.05)
	  	time.sleep(3)
	  	clear_screen()
	  	fail_display(" Trông cute phết nhỉ...")
	  	

def moment_2():
	clear_screen()
	slow_print(" *David đã lẻn ra sau viện bảo tàng* ", 0.1)
	time.sleep(1)
	clear_screen()
	slow_print(" David: Hmm... sao có thể qua được bức tường này đây nhờ?... ", 0.05)
	time.sleep(1)
	clear_screen()
	
	while True:
		clear_screen()
		actions = ["Dùng búa","Dùng TNT","Đốt tường","Dùng máy dịch chuyển cầm tay","Ăn xiên la","Dùng xẻng"]
		choice_index, selected_action = choose_menu(actions)
		
		if choice_index == 0:
			clear_screen()
			slow_print(" David: *Dùng búa đập vào tường* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Bức tường bị nức và tan rã* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David đi vào trong...*", 0.1)
			time.sleep(1)
			continue_moment2()
			break

		elif choice_index == 1:
			clear_screen()
			slow_print(" David: *Đặt TNT vào tường* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Dây kích nổ bỗng dưng bốc cháy* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: hà há, tao đã mong chờ điều này lâu lắm rồ- ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *BOOM* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: Aáaaaaa... ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David đã biến thành một cục than* ", 0.05)
			time.sleep(1)
			clear_screen()
			fail_display(" " + "Than này đem nướng chắc được lắm nhỉ...")
			
		elif choice_index == 2:
			clear_screen()
			slow_print(" David: *Lấy súng phun lửa và bắn vô bức tường* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: taooo làaaa grodannnn gramsayyyy... ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Một thời gian sau đó...", 0.1)
			time.sleep(5)
			clear_screen()
			slow_print(" *Cái tường không có hề hấn gì...*",0.1)
			time.sleep(1)
			clear_screen()
			slow_print(" David: -_- ", 0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" " + "Mày nghĩ cái tường đó làm bằng gỗ à?")
			
		elif choice_index == 3:
			clear_screen()
			slow_print(" David: *Nhìn vào cái máy* ",0.1)
			time.sleep(1)
			clear_screen()
			slow_print(" David: hm... nó dùng làm sao nhờ...",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: ...chác là bắm đại vậy...", 0.1) #Lỗi chính tả để tạo tình huống
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Bấm linh tinh vào mấy cái nút* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Một xác sau đó... ",0.1) #Lỗi chính tả tạo tình huống
			time.sleep(5)
			clear_screen()
			slow_print(" David: AAAAAA- ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David bị rơi xuống biển* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: ọc ọC ọc...",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David đã chết đuối* ", 0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" "*13 + "Tắm biển?")
			
		elif choice_index == 4:
			clear_screen()
			slow_print(" David: *Ăn xiên la* ",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: QUÁ NGON!- ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Bảo vệ nghe thấy tiếng động* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Ventic: chắc là tôi nên đi kiểm tra thử nhỉ?...",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Bảo vệ đi tới* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Ventic: CÓ KẺ ĐỘT NHẬP!", 0.04)
			time.sleep(1)
			clear_screen()
			slow_print(" David: -_- ", 0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" Ngon... ngon thiệt...")
			
		elif choice_index == 5:
			clear_screen()
			slow_print(" David: *Đào thẳng xuống* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: chắc chắn hôm nay t- ", 0.05)
			time.sleep(0.5)
			clear_screen()
			slow_print(" *Cái xẻng đâm trúng bình gas gầm* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: một cục đá á?- ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *BOOMMM* ", 0.05)
			time.sleep(2)
			clear_screen()
			fail_display(" Đừng bao giờ đào thẳng xuống...")
	        
#==========Lối chơi: Xông thẳng============
def continue_moment1_3():
	clear_screen()
	
	while True:
		clear_screen()
		actions = ["Đi thẳng","Dùng cannon","Thuốc tàng hình","Giả dạng nhân viên","Ăn cupcake"]
		choice_index, selected_action = choose_menu(actions)
		
		if choice_index == 0: #sai
			clear_screen()
			slow_print(" David: *Đi thẳng tới* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Cảnh sát: *Nghi ngờ* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Cảnh sát: NÀY ANH KIA GIƠ TAY LÊN! ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Giơ tay* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: :/",0.1)
			time.sleep(1)
			clear_screen()
			fail_display("        Thật tự tin...")
				
		elif choice_index == 1: #sai
			clear_screen()
			slow_print(" David: *Chui vào cannon* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *Cannon bắn David vô trần nhà* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: aaaaaa-", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David rớt xuống* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: AAAAAAAA-",0.05)
			time.sleep(1)
			clear_screen()
			fail_display(" Khẩu pháo bắn người?")
			
				
		elif choice_index == 2: #sai
			clear_screen()
			slow_print(" David: *Uống thuốc tàng hình*",0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David tàng hình đi qua...", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" [Vextc Systeam]: *Tìm kiếm nhân vật của người chơi* ", 0.05)
			time.sleep(5)
			clear_screen()
			slow_print(" [Vextc Systeam]: *Không tìm thấy*", 0.05)
			time.sleep(1)
			clear_screen()
			clear_screen()
			slow_print(" [Vextc Systeam]: Lỗi, không tìm thấy nhân vật của người chơi...", 0.05)
			time.sleep(1)
			clear_screen()
			fail_display("         ừ, lỗi đấy :/")
			
			
		elif choice_index == 3:
			clear_screen()
			slow_print(" David: *Mặc đồ nhân viên* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: *Đi ra ngoài* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" Cảnh sát: *Nhìn David* ", 0.05)
			time.sleep(5)
			clear_screen()
			slow_print(" Cảnh sát: *Bỏ qua David* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" *David đã chạy ra ngoài cùng với cái xô* ", 0.05)
			time.sleep(1)
			clear_screen()
			complete_display(" "*10 + "David: Giàu rồi ;)")
			
			
		elif choice_index == 4:
			clear_screen()
			slow_print(" David: *Ăn cupcake* ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: ngon :) ", 0.05)
			time.sleep(1)
			clear_screen()
			slow_print(" David: ... ", 0.1)
			time.sleep(2)
			clear_screen()
			fail_display("       Chỉ vậy thôi à?")
		
def continue_moment1_2():
      clear_screen()
      slow_print(" *David đã tới thành công viên fitum*", 0.1)
      time.sleep(1)
      clear_screen()
      slow_print(" *Chọn cách lấy nó trước khi bảo vệ tới!* ", 0.1)
      time.sleep(1)
      
      while True:
      	clear_screen()
      	actions = ["Máy hút","Balo","Dây thừng","Thùng xốp","Xô nước"]
      	choice_index, selected_action = choose_menu(actions)
      	
      	if choice_index == 0: #sai
      	   clear_screen()
      	   slow_print(" David: *Bật máy hút*",0.1)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *Máy hút hoá thành vòi rồng* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" David: AAAAA- ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *David bị hút ngược vào máy* ",0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   fail_display(" Nên đọc kỉ hướng dẫn sử dụng... ")
      	   
      	elif choice_index == 1: #sai
      		clear_screen()
      		slow_print(" David: *Mở balo* ", 0.1)
      		time.sleep(1)
      		clear_screen()
      		slow_print(" *Một tờ giấy rớt ra* ", 0.1)
      		time.sleep(1)
      		clear_screen()
      		slow_print(" *David đọc tờ giấy* ", 0.1)
      		time.sleep(1)
      		clear_screen()
      		
      		print("=========HSSD=========")
      		print(" Balo này có thể chứa mọi thứ mà nó có thể, trừ các vật sáng bóng hay gì đó quá cứng. Loại balo này thường đựng đồ ăn... ")
      		print("============_==========")
      		input("        [Enter để tiếp tục]")
      		
      		time.sleep(1)
      		clear_screen()
      		slow_print(" *David bỏ viên kim cương vào balo* ", 0.05)
      		time.sleep(1)
      		clear_screen()
      		slow_print(" *Bổng dưng cái balo nóng lên và cháy* ", 0.05)
      		time.sleep(1)
      		clear_screen()
      		slow_print(" David: AAAAA- ", 0.05)
      		clear_screen()
      		fail_display("      Bao lô đồ ăn?")
      		
      		   
      	elif choice_index == 2: #sai
      	   clear_screen()
      	   slow_print(" David: *Quấn dây thừng vào viên fitum* ",0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *Cái dây thừng bổng dưng bị đứt* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" David: -_-", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *Bảo vệ lao tới* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" Bảo vệ: cuối cùng củng bắt được mày rồi nhóc!", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   fail_display(" Ừ, cái này nó giống dây quần nhỉ...")
      	   
      	   
      	   
      	elif choice_index == 3: #sai
      	   clear_screen()
      	   slow_print(" Daivd: *Bỏ viên fitum vào thùng xốp* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *Bổng nhiên cái thùng xốp có một con cún* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" Con cún: *Gặm viên fitum và chạy mất* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" Daivd: ._. ", 0.1)
      	   time.sleep(1)
      	   clear_screen()
      	   fail_display("   PETA rất thích điều này...")
      	
      	elif choice_index == 4: #đúng
      	   clear_screen()
      	   slow_print(" Daivd: *Bỏ viên fitum vào xô* ", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" Daivd: *Đi tới cổng chính*", 0.05)
      	   time.sleep(1)
      	   clear_screen()
      	   slow_print(" *Ở trước cổng có rất nhiều cảnh sát và bảo vệ, tìm cách cho David trốn thoát*", 0.05)
      	   time.sleep(1) 
      	   continue_moment1_3()
      	   break

def continue_moment1():
    slow_print(" *David đang xông vô trước sảnh của viện bảo tàng* ", 0.05)
    time.sleep(0.5)
    clear_screen()
    slow_print(" (Trong lúc đó...) ", 0.1)
    time.sleep(1)
    clear_screen()
    slow_print(" Simla: Ê béoluga, mày nghĩ sau khi kết thúc giờ làm nên đi đâu chơi không?...", 0.1)
    time.sleep(1)
    clear_screen()
    slow_print(" Beluga: m gọi tao LÀ GÌ?", 0.05)
    time.sleep(1)
    clear_screen()
    slow_print(" Simla: ô kê xiêm- ", 0.1)
    time.sleep(0.9)
    clear_screen()
    slow_print(" *David đang lao tới cùng với cái ván trượt* ", 0.05)
    time.sleep(1)
    clear_screen()
    slow_print(" Simla: một thằng nhóc với cái ván trượt á?...", 0.1)
    clear_screen()
    slow_print(" Beluga: *trốn* ", 0.05)
    time.sleep(1)
    clear_screen()
    slow_print(" Simla: Được rồi để Xiêm lo liệu- ", 0.05)
    time.sleep(0.5)
    
    while True:
        clear_screen()
        actions = ["Dùng súng bắn Simla ", "Full tốc độ", "Khiên bong bóng", "Niệm chú"]
        choice_index, selected_action = choose_menu(actions)
        
        if choice_index == 0: #sai
            clear_screen()
            slow_print(" *David lấy súng ra và bắn vào simla* ", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" Simla: *Né* ", 0.05)
            time.sleep(0.5)
            clear_screen()
            slow_print(" Simla: *Bắn trả* ", 0.05)
            time.sleep(0.05)
            clear_screen()
            slow_print(" *David bị một viên đạn bay vào đầu* ", 0.05)
            time.sleep(1)
            clear_screen()
            fail_display("            Heatshot!")
            
        elif choice_index == 1: #sai
            clear_screen()
            slow_print(" *David sử dụng full tốc độ của ván trượt* ", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" *Cái ván trượt quá nhanh khiến David bị rớt xuống đất* ", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" Simla: xiêm", 0.1)
            time.sleep(1)
            clear_screen()
            slow_print(" Daivd: -_- ", 0.1)#
            time.sleep(1)
            clear_screen()
            fail_display("                 xiêm")
                      
        elif choice_index == 2: #đúng
            clear_screen()
            slow_print(" *David bật khiên bong bóng* ", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" Simla: mày nghĩ cái khiên bong bóng đó cứu được mày à!", 0.05)
            time.sleep(1)
            clear_screen()
            print("Simla: ", end='')
            slow_print(" *Bắn vô bạn* ", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" *Khiên bong bóng phản đạn vô simla* ",0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" Simla: AAAAA-", 0.05)
            input("    [Enter để tiếp tục]")
            continue_moment1_2()
            break
                        
        elif choice_index == 3: #sai
        	clear_screen()
        	slow_print(" David: *Simla mu li evestea deli homio...* ", 0.02)
        	time.sleep(1)
        	clear_screen()
        	time.sleep(0.5)
        	slow_print(" David: *Simla mu li evestea deli homio...* ", 0.02)
        	time.sleep(1)
        	clear_screen()
        	slow_print(" David: *Simla mu li evestea deli homika... *", 0.02)
        	time.sleep(1)
        	slow_print(" Simla: *Bắn vô ván trượt*",0.05)
        	time.sleep(1)
        	clear_screen()
        	slow_print(" *Ván trượt bị nổ* ", 0.05)
        	time.sleep(1)
        	slow_print(" David: Aaaaaaaa...", 0.05)
        	time.sleep(1)
        	clear_screen()
        	fail_display(" Cái câu niệm này nó quen lắm... ")
        	
 #Hành động: xông thẳng  	
def moment_1():
    clear_screen()
    slow_print("\n*Tiếng máy xe*", 0.05)
    input("\n[Enter để tiếp tục]")
    clear_screen()
    slow_print("\nDavid: Hôm nay tao phải lập nên trò chống gì đó!", 0.05)
    time.sleep(1)
    
    clear_screen()
    slow_print(" *David đang lái một cái ván trượt và đâm vào cửa chính* ", 0.05)
    clear_screen()
    slow_print(" Ventic: hôm nay có lẽ khá- ", 0.1)
    slow_print(" Facto: ê có gì kìa mày! ", 0.1)
    clear_screen()
    slow_print(" *Bạn đang phóng ván trượt tới* ", 0.1)
    time.sleep(0.5)
    slow_print(" Ventic: chỉ là một thằng nhóc thôi mà-", 0.1)
    time.sleep(1)

    while True:
        clear_screen()
        actions = ["Tông bảo vệ 1 (Ventic)", "Tông bảo vệ 2 (Facto)", "Chạy ngang qua"]
        choice_index, selected_action = choose_menu(actions)
        
        if choice_index == 0:
            clear_screen()
            slow_print("David: aaaaaa...", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print("*David tông vào Ventic và bật ngả*", 0.05)
            time.sleep(1)
            clear_screen()
            fail_display(" Mày nghĩ mày là Toro à?")
        
        elif choice_index == 1:
            clear_screen()
            slow_print(" *Facto bị văng vô thùng rác và bạn đã phá luôn cái cửa chính* ", 0.05)
            time.sleep(1)
            continue_moment1() 
            break
        
        elif choice_index == 2:
            clear_screen()
            slow_print(" David: AAAAA-", 0.05)
            time.sleep(1)
            clear_screen()
            slow_print(" *David đâm sầm vào thùng rác*", 0.1)
            time.sleep(1)
            clear_screen()
            fail_display(" Tôi không nghĩ là cái thùng rác lại nằm ở đó, đúng không nhỉ?")

#=============Cutsence================
def cut_scene():
    loading_anima(dur=5)
    clear_screen()
    time.sleep(1)
    slow_print(" TV: Viện bảo tàng quốc gia đang giữ một viên ngọc cổ đại có tên fitum!...", 0.1)
    input("(Nhấn Enter để tiếp tục)")
    clear_screen()
    slow_print(" TV: Nó đang nằm giữa viện bảo tàng... ", 0.1)
    input("(Nhấn Enter để tiếp tục)")
    clear_screen()
    slow_print(" TV: Ồ chà!, viên ngọc có một màu xanh rất tự nhiên...", 0.1)
    input("(Nhấn Enter để tiếp tục)")
    clear_screen()
    slow_print(" TV: ...và trị giá của viên ngọc lên đến 250.000.000 fitum!...", 0.1)
    clear_screen()
    slow_print(" David: ...", 0.2)
    clear_screen()
    slow_print(" David: :)", 0.2)
    input("(Nhấn Enter để tiếp tục)")
    clear_screen()
    slow_print(" Bạn đã ở phía trước bảo tàng, hãy chọn hành động để vào bảo tàng", 0.1)
    clear_screen()
    
    #Xử lí hành động
    actions = ["Xông thẳng", "Lén lút"]
    choice_index, selected_action = choose_menu(actions)
    if choice_index == 0:
        moment_1()
        
    elif choice_index == 1:
        moment_2()

if __name__ == '__main__':
	cut_scene()